version: "2"
services:
  app:
    container_name: HOSPITAL_NEW
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: Mongo_New
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "32768:27017"










